name: 'Trigger Docker image build'

on:
  push:
    branches:
      - main
      - release/v[12].[0-9]+.[0-9]+ # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
  workflow_dispatch:

jobs:
  trigger:
    name: 'trigger Docker image build'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Dispatch docker builds Github Action
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          PARENT_REPO: feedmeapples/test2
          PARENT_BRANCH: ${{ toJSON('main') }}
          WORKFLOW_ID: test.yml
          REPO: ${{ toJSON('test1') }}
          BRANCH: ${ GITHUB_REF_NAME }
        run: |
          curl -fL -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$PARENT_REPO/actions/workflows/$WORKFLOW_ID/dispatches" -d '{"ref":'"$PARENT_BRANCH"', "inputs": { "repo":'"$REPO"', "branch":'"$BRANCH"' }}'
